global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s # This can be adjusted based on our needs
    static_configs:
      - targets: ['localhost:8080']